### ISSUE TITLE
Not really an issue but....

### ISSUE THREAD

**Issue by zz-james** [gunar/sam-redux#3]
how do you feel this project worked out? I am 6 months in to a build using React/Redux and I want to introduce some kind of state-machine control state architecture and SAM seems very interesting to me, I'm not really in the position to tear out all the Redux but could fairly easily refactor to this.

**Comment by gunar** [comment]
I worked out okay -- although I am not using it in production.
Since learning about SAM I've been in love with it but haven't truly applied it.
My guess is it's because I am not doing much frontend stuff lately.

SAM is so simple, it bearly needs anything else apart from code conventions / simple functions.
Personally, I would not mix in Redux. It would just add complexity.

**Comment by gunar** [comment]
Quick update. Our team is building on https://github.com/invisible-tech/samx
